dist: xenial

sudo: required
language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_CLONE="datastructures"
    - GAP_PKGS_TO_BUILD="io profiling datastructures"

addons:
  apt_packages:
      - libgmp3-dev
      - autotools-dev
      - automake

matrix:
  include:
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: CFLAGS="-O2" CC=gcc CXX=g++
      compiler: gcc
    - env: CFLAGS=""  # test build w/o optimization

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh
  - scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
