dist: xenial

language: c
env:
  global:
    - GAP_PKGS_TO_CLONE="datastructures"
    - GAP_PKGS_TO_BUILD="io profiling datastructures"
    - GAP_TESTFILE="tst/testinstall.g"

addonse:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - zlib1g-dev

matrix:
  include:
    - env: GAPBRANCH=master CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: GAPBRANCH=master CFLAGS="-O2" CC=gcc CXX=g++
      compiler: gcc
    - env: GAPBRANCH=master CFLAGS=""  # test build w/o optimization
    - env: GAPBRANCH=stable-4.11 CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: GAPBRANCH=stable-4.11 CFLAGS="-O2" CC=gcc CXX=g++
      compiler: gcc
    - env: GAPBRANCH=stable-4.11 CFLAGS=""  # test build w/o optimization
    - env: GAPBRANCH=master # also test on macOS (uses clang)
      os: osx

branches:
  only:
    - master

before_script:
  - git clone https://github.com/gap-system/pkg-ci-scripts.git scripts
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh && scripts/run_tests.sh
after_script:
  - scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
