dist: trusty
language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev

matrix:
  include:
    - env: CFLAGS="-O2"
      compiler: clang
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: CFLAGS=""  # test build w/o optimization

branches:
  only:
    - master

before_script:
  - scripts/build_gap.sh
script:
  - scripts/build_pkg.sh
  - scripts/run_tests.sh
after_script:
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
